apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vs-destination-rule","deployment":"vs-destination-rule-v1"},"name":"vs-destination-rule-v1","namespace":"0-vs"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"vs-destination-rule","deployment":"vs-destination-rule-v1"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"creationTimestamp":null,"labels":{"app":"vs-destination-rule","deployment":"vs-destination-rule-v1"}},"spec":{"containers":[{"env":[{"name":"PRIMARY_COLOR","value":"FF00FF"},{"name":"SECONDARY_COLOR","value":"8000FF"}],"image":"image-registry.openshift-image-registry.svc:5000/xpk/app-base@sha256:c5ad2a167f9c7fd98aa48997647e3ab0ddba6dfd8a86b3fdef68ba83fd73bf36","imagePullPolicy":"IfNotPresent","name":"vs-destination-rule-v1","ports":[{"containerPort":5000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2025-06-02T17:59:54Z"
  generation: 1
  labels:
    app: vs-destination-rule
    deployment: vs-destination-rule-v1
  name: vs-destination-rule-v1
  namespace: 0-vs
  resourceVersion: "379594"
  uid: fcfad0c7-2fc6-4f81-8e52-3e19c69b956c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vs-destination-rule
      deployment: vs-destination-rule-v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: vs-destination-rule
        deployment: vs-destination-rule-v1
    spec:
      containers:
      - env:
        - name: PRIMARY_COLOR
          value: FF00FF
        - name: SECONDARY_COLOR
          value: 8000FF
        image: image-registry.openshift-image-registry.svc:5000/xpk/app-base@sha256:c5ad2a167f9c7fd98aa48997647e3ab0ddba6dfd8a86b3fdef68ba83fd73bf36
        imagePullPolicy: IfNotPresent
        name: vs-destination-rule-v1
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-02T17:59:54Z"
    lastUpdateTime: "2025-06-02T17:59:56Z"
    message: ReplicaSet "vs-destination-rule-v1-77bb5b9b9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-02T20:36:34Z"
    lastUpdateTime: "2025-06-02T20:36:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
