# Default values for git-clone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pvc:
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClassName: ""

git:
  hostname: your.git.host
  authType: basic
  revision: main
  verbose: true
  sslVerify: true

repository:
  registryUrl: image-registry.openshift-image-registry.svc:5000
  imageName: myname
  tag: latest
  gitPathContext: /
  gitDockerfile: Containerfile
  sslVerify: false